/*
 * generated by Xtext 2.29.0
 */
package kcl.ac.uk.ui.tests;

import com.google.inject.Injector;
import kcl.ac.uk.WeebADoodle.ui.internal.WeebADoodleActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class WeebADoodleUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return WeebADoodleActivator.getInstance().getInjector("kcl.ac.uk.WeebADoodle");
	}

}
