/*
 * generated by Xtext 2.29.0
 */
package kcl.ac.uk.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import kcl.ac.uk.WeebADoodleRuntimeModule;
import kcl.ac.uk.WeebADoodleStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class WeebADoodleIdeSetup extends WeebADoodleStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new WeebADoodleRuntimeModule(), new WeebADoodleIdeModule()));
	}
	
}
