/*
 * generated by Xtext 2.29.0
 */
package kcl.ac.uk.parser.antlr;

import com.google.inject.Inject;
import kcl.ac.uk.parser.antlr.internal.InternalWeebADoodleParser;
import kcl.ac.uk.services.WeebADoodleGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class WeebADoodleParser extends AbstractAntlrParser {

	@Inject
	private WeebADoodleGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalWeebADoodleParser createParser(XtextTokenStream stream) {
		return new InternalWeebADoodleParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public WeebADoodleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(WeebADoodleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
