/*
 * generated by Xtext 2.29.0
 */
package kcl.ac.uk.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWeebADoodleScopeProvider extends DelegatingScopeProvider {
}
