/*
 * generated by Xtext 2.29.0
 */
package kcl.ac.uk.ui;

import com.google.inject.Injector;
import kcl.ac.uk.WeebADoodle.ui.internal.WeebADoodleActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WeebADoodleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(WeebADoodleActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		WeebADoodleActivator activator = WeebADoodleActivator.getInstance();
		return activator != null ? activator.getInjector(WeebADoodleActivator.KCL_AC_UK_WEEBADOODLE) : null;
	}

}
